class estabelecimentosAlimenticios(object):
    """description of class"""
    razaosocial = ""
    nomefantasia = ""
    cnpj = ""
    naturezajuridica = ""
    datainicio = ""
    porte = ""
    situacao = ""
    tipoatividade = ""
    subtipo = ""
    cep = ""
    uf = ""
    localidade = ""
    bairro = ""
    logradouro = ""
    telefone = ""
    fax = ""
    email2 = ""
    email3 = ""
    site = ""
    codigocertificado = ""
    codigodescricaocnae = ""
    capacidade = ""
    linguas = ""
    latitude = 0.0
    longitude = 0.0
    def __init__(self, razaosocial, nomefantasia, cnpj, naturezajuridica, datainicio, porte, situacao, tipoatividade, subtipo, cep, uf, localidade, bairro, logradouro, telefone, fax, email2, email3, site, codigocertificado, codigodescricaocnae, capacidade, linguas):
        self.razaosocial = razaosocial 
        self.nomefantasia = nomefantasia
        self.cnpj = cnpj
        self.naturezajuridica = naturezajuridica
        self.datainicio = datainicio
        self.porte = porte
        self.situacao = situacao
        self.tipoatividade = tipoatividade
        self.subtipo = subtipo
        self.cep = cep
        self.uf = uf
        self.localidade = localidade
        self.bairro = bairro
        self.logradouro = logradouro
        self.telefone = telefone
        self.fax = fax
        self.email2 = email2
        self.email3 = email3
        self.site = site
        self.codigocertificado = codigocertificado
        self.codigodescricaocnae = codigodescricaocnae
        self.capacidade = capacidade
        self.linguas = linguas


